# Generated by Django 3.1.5 on 2021-01-29 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmodel',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='Paper.docxmodel'),
        ),
    ]
