# Generated by Django 3.1.5 on 2021-02-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0003_auto_20210129_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listmodel',
            old_name='title',
            new_name='topic',
        ),
        migrations.AlterField(
            model_name='listmodel',
            name='endDate',
            field=models.DateField(default='2021-02-02'),
        ),
    ]
