# Generated by Django 3.1.5 on 2021-02-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0005_auto_20210204_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docxmodel',
            name='user',
        ),
    ]
