# Generated by Django 3.1.5 on 2021-02-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0007_docxmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listmodel',
            old_name='endDate',
            new_name='Due_Date',
        ),
    ]
